[package]
name = "axconsole"
version = "0.1.0"
edition = "2024"

description = "A brief description of your crate"
license = "Apache-2.0 OR MIT" 
repository = "https://github.com/Josen-B/axconsole.git"


[dependencies]

