[package]
name = "axconsole"
version = "0.3.0"
authors = ["QiaoSen Bai <baiqiaosen2021@163.com>"]
edition = "2024"

description = "A brief description of your crate"
license = "Apache-2.0 OR MIT" 
repository = "https://github.com/Josen-B/axconsole.git"


[dependencies]
log = "0.4"
